CREATE TABLE [dbo].[templist](
[phone] [nvarchar](max) NULL,
[lastname] [nvarchar](max) NULL,
[name] [nvarchar](max) NULL,
[middlename] [nvarchar](max) NULL,
[category] [nvarchar](max) NULL,
[sex] [nvarchar](max) NULL,
[city] [nvarchar](max) NULL,
[birthday] [nvarchar](max) NULL
) ON [PRIMARY]
