//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactListMvc.Models.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class personattribute
    {
        public int id { get; set; }
        public int idperson { get; set; }
        public int idattribute { get; set; }
        public string val { get; set; }
    
        public virtual attribute attribute { get; set; }
        public virtual person person { get; set; }
    }
}
